[admin]

enabled = true
main = discord

[discord]

token = "YOUR_TOKEN_HERE"

[twitch]

nick = "chatmux"
token = "YOUR_TOKEN_HERE" # https://twitchtokengenerator.com/

[mixer]

client_id = "YOUR_APP_ID"
token = "YOUR_TOKEN_HERE" # https://dev.mixer.com/guides/chat/chatbot (click the text that says "click here to get your token")

[permissions]

# tterrag1098
[[admins]] # Admins can do everything (ban, timeout, purge)
discord = 140245257416736769

[[moderators]] # Moderators can only timeout/purge